[transform]
expressions = [
    'C_0_T=hash(concat("C-0",C_0))',
    'C_1_T=hash(concat("C-1",C_1))',
    'C_2_T=hash(concat("C-2",C_2))',
    'C_3_T=hash(concat("C-3",C_3))',
    'C_4_T=hash(concat("C-4",C_4))',
    'C_5_T=hash(concat("C-5",C_5))',
    'C_6_T=hash(concat("C-6",C_6))',
    'C_7_T=hash(concat("C-7",C_7))',
    'C_8_T=hash(concat("C-8",C_8))',
    'C_9_T=hash(concat("C-9",C_9))',
    'C_10_T=hash(concat("C-10",C_10))',
    'C_11_T=hash(concat("C-11",C_11))',
    'C_12_T=hash(concat("C-12",C_12))',
    'C_13_T=hash(concat("C-13",C_13))',
    'C_14_T=hash(concat("C-14",C_14))',
    'C_15_T=hash(concat("C-15",C_15))',
    'C_16_T=hash(concat("C-16",C_16))',
    'C_17_T=hash(concat("C-17",C_17))',
    'C_18_T=hash(concat("C-18",C_18))',
    'C_19_T=hash(concat("C-19",C_19))',
    'C_20_T=hash(concat("C-20",C_20))',
    'C_21_T=hash(concat("C-21",C_21))',
    'C_22_T=hash(concat("C-22",C_22))',
    'C_23_T=hash(concat("C-23",C_23))',
    'C_24_T=hash(concat("C-24",C_24))',
    'C_25_T=hash(concat("C-25",C_25))',
    'I_0_T=hash(concat("I_0", to_string(ceil(I_0))))',
    'I_1_T=hash(concat("I_1", to_string(ceil(I_1))))',
    'I_2_T=hash(concat("I_2", to_string(ceil(I_2))))',
    'I_3_T=hash(concat("I_3", to_string(ceil(I_3))))',
    'I_4_T=hash(concat("I_4", to_string(ceil(I_4))))',
    'I_5_T=hash(concat("I_5", to_string(ceil(I_5))))',
    'I_6_T=hash(concat("I_6", to_string(ceil(I_6))))',
    'I_7_T=hash(concat("I_7", to_string(ceil(I_7))))',
    'I_8_T=hash(concat("I_8", to_string(ceil(I_8))))',
    'I_9_T=hash(concat("I_9", to_string(ceil(I_9))))',
    'I_10_T=hash(concat("I_10", to_string(ceil(I_10))))',
    'I_11_T=hash(concat("I_11", to_string(ceil(I_11))))',
    'I_12_T=hash(concat("I_12", to_string(ceil(I_12))))',
]
features = [
    "C_0_T",
    "C_1_T",
    "C_2_T",
    "C_3_T",
    "C_4_T",
    "C_5_T",
    "C_6_T",
    "C_7_T",
    "C_8_T",
    "C_9_T",
    "C_10_T",
    "C_11_T",
    "C_12_T",
    "C_13_T",
    "C_14_T",
    "C_15_T",
    "C_16_T",
    "C_17_T",
    "C_18_T",
    "C_19_T",
    "C_20_T",
    "C_21_T",
    "C_22_T",
    "C_23_T",
    "C_24_T",
    "C_25_T",
    "I_0_T",
    "I_1_T",
    "I_2_T",
    "I_3_T",
    "I_4_T",
    "I_5_T",
    "I_6_T",
    "I_7_T",
    "I_8_T",
    "I_9_T",
    "I_10_T",
    "I_11_T",
    "I_12_T",
]
